### ISSUE TITLE
Impossible de sauvegarder sur le serveur

### ISSUE THREAD

**Issue by inkskull** [YunoHost-Apps/tiddlywiki_ynh#1]
Bonjour, 

Je viens d'installer tiddlywicki sur mon serveur yunohost

Bravo pour cette adaptation. J'avais essayé de le faire moi même mais faute de temps je n'ai jamais fini...

Avez-vous trouvé une solution pour sauvegarder les modifications sur le serveur? Je viens d'installer tiddlywicki sur mon serveur yunohost et lorsque je sauvegarde les modifications par défaut ça télécharque le wicki sur mon poste de travail ce qui n'est pas vraiement ce que je souhaitais.

**Comment by ericgaspar** [comment]
Ce comportement où un fichier html est sauvé a l’air normal (cf. le site démonstration)
 Tiddlywiki est conceptuellement déroutant. Il y a plusieurs manières de sauvegarder les pages wiki. Tu peux sans doute essayer de voir dans `ControlPanel`, menu `Saving`. Il y a plusieurs possibilités de sauvegardes dont GitHub, GitLab et Gitea…

**Comment by inkskull** [comment]
Ok je m'en doutais un peu, J'utilise depuis plusieurs années Tiddlycki pour sauvegarder mes recettes de cuisines et la façon de sauvergarder les modification ne me satisfaisait pas complètement puisq'une fois celle-ci effectuer il faut effectuer un déplacement/renommage de fichier ou quelques chose d'équivalent pour retrouver le fichier modifié a la place du fichier initial (je sais pas si c'est super clair). Je pense que pour sauvegarder directement sur le serveur il faudrait utiliser la version node.js de tiddlywicki.  Je vais continuer de chercher. Merci

**Comment by ericgaspar** [comment]
@inkskull la version TiddlyWiki sous Node.js est maintenant disponible sur la branche master.
`sudo yunohost app install https://github.com/YunoHost-Apps/tiddlywiki_ynh`

**Comment by inkskull** [comment]
@ericgaspar J'ai mis un peu de temps tester la version node.js... Je n'avais pas compris que le mot de passe demandé à l'installation doit être le mot de passe yunohost de l'utilisateur désigné comme admin de tiddlywiki... Quoi qu'il en soit ça fonctionne très bien, la sauvegarde se fait de façon transparente et j'ai pu récupérer mon wiki local en deux clics. Un grand merci Eric pour cette intégration.
