### ISSUE TITLE
Node.js : données perdues lors du redémarrage du serveur

### ISSUE THREAD

**Issue by davidszerman** [YunoHost-Apps/tiddlywiki_ynh#10]
Bonjour,

je viens d'installer tiddlywiki sur mon yunohost.

Tout fonctionne parfaitement, les modifications SEMBLENT sauvegardées (je me connecte de différents navigateurs et voient les modifications) mais en fait, c'est juste dans le cache serveur ; si je redémarrer physiquement le serveur, toutes les données sont perdues et je me retrouve avec un tiddlywiki vierge  :-(

Merci poru votre aide

**Comment by ericgaspar** [comment]
Effectivement il y a un problème avec la commande `--init server`...
peux-tu tester la branche testing 
`sudo yunohost app install https://github.com/YunoHost-Apps/tiddlywiki_ynh/tree/testing`
Désolé pour ce contretemps 😨

**Comment by davidszerman** [comment]
C'est ok pour cette branche, merci   :-)
