### ISSUE TITLE
Commandes shell tiddlywiki ?

### ISSUE THREAD

**Issue by davidszerman** [YunoHost-Apps/tiddlywiki_ynh#12]
Bonjour,

en me renseignant sur Tiddlywiki sur node.js, j'ai cru comprendre qu'il était possible de lancer certaines commandes, comme : 

tiddlywiki wikipath --rendertiddlers '[!is[system]]' $:/core/templates/static.tiddler.html static text/plain
tiddlywiki wikipath --rendertiddler $:/core/templates/static.template.html static.html text/plain
tiddlywiki wikipath --rendertiddler $:/core/templates/static.template.css static/static.css text/plain

Sur mon install yunohost, tiddlywiki n'est pas une commande connue ; y a t il moyen de l'appeler ?

Merci

**Comment by ericgaspar** [comment]
It should be something like this. (please adapt to your needs)
`sudo /opt/node_n/n/versions/node/14/bin/node /var/www/tiddlywiki/tiddlywiki  [<wikifolder>] [--<command> [<args>...]...]`

**Comment by davidszerman** [comment]
Perfect, thanks
