### ISSUE TITLE
Password containing the % character causes installation via web-interface to fail

### ISSUE THREAD

**Issue by JoMiHa** [YunoHost-Apps/tiddlywiki_ynh#14]
### Describe the bug

When installing using the ynh-webadmin interface, using a password containing the % character causes the installation to fail.

### Context

- Hardware: rpi3
- YunoHost version: 4.2.8
- I have access to my server: Through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: N/A
- If upgrading, current package version: N/A

### Steps to reproduce

- Log into webadmin interface
- Configure an install of tiddlywiki_ynh
- When selecting the admin-user and p/w, use a password containing a % character
-- The p/w I tried to use contained "%e" (in case there are valid %-identifiers)
- Click install, wait...
- Installation fails

### Expected behavior

Either 1) using the % character in your password should not cause the install to fail, or 2) this should be mentioned during install.

### Workaround

- Do not use a password containing the % character.

**Comment by ericgaspar** [comment]
Thanks for pointing it out. For now, a mention during installation should warn about special characters in the password (I hope we will come up with a more satisfactory solution in the future...)
