### ISSUE TITLE
Support multiple users on the same Yunohost?

### ISSUE THREAD

**Issue by johanbove** [YunoHost-Apps/tiddlywiki_ynh#23]
### Describe the bug

Expected that a TiddlyWiki installed on a Yunohost would be individual for each user (using SSO) but in reality the TiddlyWiki is shared between all users by default. 

### Context

- Hardware: Raspberry Pi 3 B at home
- YunoHost version: YunoHost 4.3.6.2 (stable)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: NO
  - If yes, please explain:
- Using, or trying to install package version/branch: `5.1.23~ynh5`

### Steps to reproduce

- Install the TiddlyWiki app and assign a domain
- Open the app on the assigned domain
- The app opens fine and can be used and data is saved.

### Expected behavior

It would be cool if the "shared Tiddlywiki" aspect was optional and that more than a single TiddlyWiki instance could be installed so every user has their own TiddlyWiki.

### Logs

No logs.

**Comment by yalh76** [comment]
Even if it could be possible, it would be complicated to do so, it requires:

- [ ] having sso working on tiddlywiki
- [ ] having some hooks to create a tiddlywiki for each user, deleting when user is removed, etc ...

**Comment by ericgaspar** [comment]
Tiddlywiki seems to be not suited to handle multiple users at the same time (there is a plugin -> Bob)
