### ISSUE TITLE
New Version 5.2.3 / Updater script using releases instead of tags

### ISSUE THREAD

**Issue by mdeabreu** [YunoHost-Apps/tiddlywiki_ynh#29]
### Describe the bug

This is both a request to get the latest upstream version (5.2.3 at time of writing) and a bug report about the updater.sh/yml scripts incorrectly using the upstream "[Releases](https://github.com/Jermolene/TiddlyWiki5/releases)" (which is completely empty) instead of the correct "[Tags](https://github.com/Jermolene/TiddlyWiki5/tags)" which seems to be how upstream is tracking their updates.

### Steps to reproduce

- View [upstream releases](https://github.com/Jermolene/TiddlyWiki5/releases), notice there are none
- View [upstream tags](https://github.com/Jermolene/TiddlyWiki5/tags), notice latest version is 5.2.3
- Notice updater Github action incorrectly reports no new version (arbitrary but recent action [run logs](https://github.com/YunoHost-Apps/tiddlywiki_ynh/actions/runs/2987088762))

### Expected behavior

Updater script should either update to match upstream or at least alert that there is a new upstream version

**Comment by ericgaspar** [comment]
Tiddlywiki as been manually updated to 5.2.3

**Comment by pmario** [comment]
TW doesn't use releases because The information about the changes are tracked at https://tiddlywiki.com/#Releases

@ericgaspar .. You mentioned that TW needed to be updated manually. .. What will be needed to be able to have an automatic update?
