### ISSUE TITLE
TiddlyWiki license is BSD 3-clause -- please update

### ISSUE THREAD

**Issue by pmario** [YunoHost-Apps/tiddlywiki_ynh#32]
The TiddlyWiki License is BSD 3 clause as can be seen at: https://github.com/Jermolene/TiddlyWiki5/blob/master/license

The manifest.js states it's BSD 2 clause, which is wrong.

https://github.com/YunoHost-Apps/tiddlywiki_ynh/blob/master/manifest.json#L12

**Comment by ericgaspar** [comment]
fixed in #35
