### ISSUE TITLE
Not able to log-in on freshly installed instance of tiddlywiki

### ISSUE THREAD

**Issue by gked** [YunoHost-Apps/tiddlywiki_ynh#8]
Hey All,

After installing the tiddlywiki instance on yunohost, and navigating to the url,  I am not able to log-in using the account under which I installed it. Logging-in with an admin account doesn't work either.

Did I miss anything in the instructions or is it a bug?

Thanks!

**Comment by unedeplus** [comment]
Hi, 
Same happened to me on a fresh install.  Login credential not correct...  Maybe sso on another domain doesn't work ?

**Comment by ericgaspar** [comment]
Please give more details, logs, steps to reproduce, something... !
If you don't give any detail on how to reproduce you issue, we are just left with guessing ... 

I have installed it on a sub domain and I have acces to Tiddlywiki (whithout the need to enter username/password).
My guess: try to register during installation with the same `user / password` that you use to log into your YunoHost account.

**Comment by exfrog** [comment]
Hi All.
I had the same problem
tiddly installed on a nohost.me subdomain
configured with existing user and new password
presented with the yuno host sso screen, then a browser auth popup
no combo of usernames and passwords would work.

I even updated all the packages.

BUT THEN, i tried to reboot, and everything worked afterward (using my standard yunohost username with no @domain.com, and the password i configured at install)

So to those with the same problem, i hate to say it, but did you try turning it off and back on again?

**Comment by unedeplus** [comment]
Hi Eric, 
thank you for your quick reply ! 
I don't really know how to access specific logs that could help you but I will try to be more descriptive ;-)
I tried the solution proposed by exfrog : I firsrt upgrade the system and applications. Rebooted.
Tiddlywiki now works on a sub domain.  The problem is now that other app such as nextcloud or invoiceninja didn't like the update and are broken now ... 
I'm running yunohost on a RPI with version 4.2.5.2 (stable)

**Comment by gked** [comment]
@ericgaspar I haven't observed any errors during the installation.
I would be more than happy to share the logs if you could let me know where they are stored.

**Comment by ericgaspar** [comment]
Useful logs are found in the webadmin -> services -> tiddlywiki.
Also, when you install Tiddlywiki, try to use the same credentials you use to log into your YunoHost session.

**Comment by joe-hudson** [comment]
Hey Eric, I’m having the same issue. Here are some logs from my server. 

`Jun 06 03:44:29 node[584]: Sync error while processing save of '$:/StoryList': Error: ENOENT: no such file or directory, open '/var/www/tiddlywiki/mynewwiki/tiddlers/$__StoryList.tid'
Jun 06 03:44:34 node[584]:  syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
Jun 06 03:44:34 node[584]: Sync error while processing save of '$:/StoryList': Error: ENOENT: no such file or directory, open '/var/www/tiddlywiki/mynewwiki/tiddlers/$__StoryList.tid'
Jun 06 03:44:39 node[584]:  syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
Jun 06 03:44:39 node[584]: Sync error while processing save of '$:/StoryList': Error: ENOENT: no such file or directory, open '/var/www/tiddlywiki/mynewwiki/tiddlers/$__StoryList.tid'
Jun 06 03:44:41 systemd[1]: Stopping TiddlyWiki: interactive wiki...
Jun 06 03:44:41 systemd[1]: tiddlywiki.service: Main process exited, code=killed, status=15/TERM
Jun 06 03:44:41 systemd[1]: tiddlywiki.service: Succeeded.
Jun 06 03:44:41 systemd[1]: Stopped TiddlyWiki: interactive wiki. `

**Comment by joe-hudson** [comment]
Update: I reinstalled using my Yunohost user credentials for the admin password and it works. There isn’t even a prompt for un/pw this time. I verified in private browser tab the it’s still being Yunohost login (I’m not sharing with the internet).

**Comment by gked** [comment]
After updating to newer version of yunohost, and re-installing tiddlywiki, the issue has disappeared.

**Comment by pbernery** [comment]
Same issue here until I set the same password in the `password` field as the one I use for logging in to YunoHost.
Without this, I am presented with a Basic Authentication alert coming from TiddlyWiki.

The message contains "Please provide your username and password to login to". It looks like it's coming from ./core/modules/server/authenticators/basic.js:85 or ./core/modules/server/routes/get-login-basic.js:23.

I don't know much the TiddlyWiki code base, but I guess the Basic Authentication are not correctly passed when used with YunoHost.

Anyway, ideally this would be better to not have to set a password and use YunoHost credentials instead.
As I said, I don't know much TiddlyWiki nor do I know how and if TiddlyWiki could be configured for that. If nobody knows, I may help in the future once my knowledge of the tool has increased :) (I'm just starting to use it).

**Comment by gked** [comment]
@pbernery have you tried updating yunohost to the newest version?
Updating yunohost has resolved the issue for me and at least one other person.

**Comment by gked** [comment]
> I did, YunoHost 4.2.7 on my machine.
> 
> Do you use different passwords for YunoHost and for TiddlyWiki?

No, i am using the same password as I use to login to YunoHost.

**Comment by pbernery** [comment]
> > I did, YunoHost 4.2.7 on my machine.
> > Do you use different passwords for YunoHost and for TiddlyWiki?
> 
> No, i am using the same password as I use to login to YunoHost.

For me, it was not working when using different passwords, I believe this is the origin of the issue.

**Comment by ashledombos** [comment]
I tried several way to install, but face the same login issue… Is there an official way ton install it?

**Comment by ericgaspar** [comment]
I have added a branch without admin/password

`sudo yunohost app install https://github.com/YunoHost-Apps/tiddlywiki_ynh/tree/passwordless`
